// js/dom.js

/**
 * Función auxiliar para obtener un elemento del DOM por su ID.
 * @param {string} id - El ID del elemento a obtener.
 * @returns {HTMLElement|null} El elemento del DOM o null si no se encuentra.
 */
export const getEl = (id) => document.getElementById(id);

/**
 * Objeto que almacena referencias a los elementos del DOM más utilizados en la aplicación.
 * Esto optimiza el acceso al DOM al evitar búsquedas repetidas.
 */
export const domElements = {
    // HUD Principal y elementos generales del juego
    saoPlayerNameDisplay: getEl('sao-player-name-display'),
    saoHpBar: getEl('sao-hp-bar'),
    playerHpCurrentText: getEl('player-hp-current'),
    playerHpMaxText: getEl('player-hp-max'),
    playerLevelText: getEl('player-level'),
    playerStatusEffectsDisplay: getEl('player-status-effects-display'), // HUD principal
    playerMpCurrentElement: getEl('player-mp-current'),
    playerMpMaxElement: getEl('player-mp-max'),
    mpBarFillElement: getEl('mp-bar-fill'),
    currentExpElement: getEl('current-exp'),
    neededExpElement: getEl('needed-exp'),
    expBarFillElement: getEl('exp-bar-fill'),
    playerColElement: getEl('player-col'),
    currentFloorElement: getEl('current-floor'),
    floorNameElement: getEl('floor-name'),

    // Botones de acción del juego (panel principal)
    combatBtn: getEl('combat-btn'),
    bossCombatBtn: getEl('boss-combat-btn'),
    questsBtn: getEl('quests-btn'),
    trainSkillBtn: getEl('train-skill-btn'),
    inventoryBtn: getEl('inventory-btn'),
    shopBtn: getEl('shop-btn'),
    blacksmithBtn: getEl('blacksmith-btn'),
    playerStatsBtn: getEl('player-stats-btn'),
    floorNavigateBtn: getEl('floor-navigate-btn'),
    adminAccessBtn: getEl('admin-access-btn'),
    saveGameBtn: getEl('save-game-btn'), // Nuevo ID
    loadGameBtn: getEl('load-game-btn'), // Nuevo ID
    newGameBtn: getEl('new-game-btn'),   // Nuevo ID


    // Modales y sus elementos internos (nombres estandarizados)
    infoModal: getEl('infoModal'),
    modalBodyContentElement: getEl('modal-body-content'),
    closeInfoModalBtn: getEl('close-info-modal-btn'),

    inventoryModal: getEl('inventoryModal'),
    inventoryGridDisplay: getEl('inventory-grid-display'),
    equipWeaponSlot: getEl('equip-weapon'),
    equipShieldSlot: getEl('equip-shield'),
    equipArmorSlot: getEl('equip-armor'),
    equipAccessorySlot: getEl('equip-accessory'),
    closeInventoryModalBtn: getEl('close-inventory-modal-btn'),

    shopModal: getEl('shopModal'),
    shopFloorNumberElement: getEl('shop-floor-number'),
    shopPlayerColElement: getEl('shop-player-col'),
    shopGridDisplay: getEl('shop-grid-display'),
    closeShopModalBtn: getEl('close-shop-modal-btn'),

    blacksmithModal: getEl('blacksmithModal'),
    blacksmithFloorNumberElement: getEl('blacksmith-floor-number'),
    blacksmithPlayerColElement: getEl('blacksmith-player-col'),
    blacksmithGridDisplay: getEl('blacksmith-grid-display'),
    playerMaterialsListElement: getEl('player-materials-list'),
    closeBlacksmithModalBtn: getEl('close-blacksmith-modal-btn'),

    playerStatsModal: getEl('playerStatsModal'),
    statsPlayerName: getEl('stats-player-name'),
    statsLevel: getEl('stats-level'),
    statsHp: getEl('stats-hp'),
    statsMp: getEl('stats-mp'),
    statsExp: getEl('stats-exp'),
    statsCol: getEl('stats-col'),
    statsBaseAtk: getEl('stats-base-atk'),
    statsBaseDef: getEl('stats-base-def'),
    statsEquipAtk: getEl('stats-equip-atk'),
    statsEquipDef: getEl('stats-equip-def'),
    statsEquipHp: getEl('stats-equip-hp'),
    statsTotalAtk: getEl('stats-total-atk'),
    statsTotalDef: getEl('stats-total-def'),
    statsSkillsList: getEl('stats-skills-list'),
    statsPassiveSkillsList: getEl('stats-passive-skills-list'),
    closePlayerStatsModalBtn: getEl('close-player-stats-modal-btn'),

    combatModal: getEl('combatModal'),
    combatTitle: getEl('combat-title'),
    combatPlayerDisplay: getEl('combat-player-display'),
    combatPlayerName: getEl('combat-player-name'),
    combatPlayerHpBar: getEl('combat-player-hp-bar'),
    combatPlayerHpCurrent: getEl('combat-player-hp-current'),
    combatPlayerHpMax: getEl('combat-player-hp-max'),
    combatPlayerMpCurrent: getEl('combat-player-mp-current'),
    combatPlayerMpMax: getEl('combat-player-mp-max'),
    combatPlayerAtk: getEl('combat-player-atk'),
    combatPlayerDef: getEl('combat-player-def'),
    combatPlayerStatusEffectsDisplay: getEl('combat-player-status-effects-display'),
    combatEnemyDisplay: getEl('combat-enemy-display'),
    combatEnemyName: getEl('combat-enemy-name'),
    combatEnemyIcon: getEl('combat-enemy-icon'),
    combatEnemyHpBarsContainer: getEl('combat-enemy-hp-bars-container'),
    combatEnemyHpBarFill: getEl('combat-enemy-hp-bar-fill'),
    combatEnemyHpCurrent: getEl('combat-enemy-hp-current'),
    combatEnemyHpMax: getEl('combat-enemy-hp-max'),
    combatEnemyAtk: getEl('combat-enemy-atk'),
    combatEnemyDef: getEl('combat-enemy-def'),
    combatEnemyStatusEffectsDisplay: getEl('combat-enemy-status-effects-display'),
    combatActionAttackBtn: getEl('combat-action-attack'),
    combatActionSkillsBtn: getEl('combat-action-skills'),
    combatActionPotionsBtn: getEl('combat-action-potions'),
    combatActionFleeBtn: getEl('combat-action-flee'),
    combatSkillsListContainer: getEl('combat-skills-list-container'),
    combatPotionsListContainer: getEl('combat-potions-list-container'),
    combatLogDisplay: getEl('combat-log-display'),
    closeCombatModalBtn: getEl('close-combat-modal-btn'),

    nameEntryModal: getEl('nameEntryModal'),
    playerNameInput: getEl('playerNameInput'),
    submitPlayerNameBtn: getEl('submitPlayerNameBtn'),
    closeNameEntryModalBtn: getEl('close-name-entry-modal-btn'),

    floorNavigationModal: getEl('floorNavigationModal'),
    floorSelectGrid: getEl('floor-select-grid'),
    closeFloorNavModalBtn: getEl('close-floor-nav-modal-btn'),

    trainingModal: getEl('trainingModal'),
    trainingPlayerCol: getEl('training-player-col'),
    trainingStatsPreview: getEl('training-stats-preview'),
    trainingGridDisplay: getEl('training-grid-display'),
    closeTrainingModalBtn: getEl('close-training-modal-btn'),
    
    questsModal: getEl('questsModal'),
    availableQuestsList: getEl('available-quests-list'),
    activeQuestsList: getEl('active-quests-list'),
    completedQuestsList: getEl('completed-quests-list'),
    questDetailsArea: getEl('quest-details-area'),
    questDetailTitle: getEl('quest-detail-title'),
    questDetailDescription: getEl('quest-detail-description'),
    questDetailObjectives: getEl('quest-detail-obj-list'),
    questDetailRewards: getEl('quest-detail-rewards-list'),
    questDetailProgressBar: getEl('quest-progress-bar-fill'),
    claimQuestRewardBtn: getEl('claim-quest-reward-btn'),
    closeQuestsModalBtn: getEl('close-quests-modal-btn'),

    adminKeyModal: getEl('adminKeyModal'),
    adminKeyInput: getEl('adminKeyInput'),
    submitAdminKeyBtn: getEl('submitAdminKeyBtn'),
    closeAdminKeyModalBtn: getEl('close-admin-key-modal-btn'),

    adminPanelModal: getEl('adminPanelModal'),
    adminLevelValueInput: getEl('adminLevelValue'),
    adminGiveExpValueInput: getEl('adminGiveExpValue'),
    adminGiveColValueInput: getEl('adminGiveColValue'),
    adminSetBaseAtkValueInput: getEl('adminSetBaseAtkValue'),
    adminSetBaseDefValueInput: getEl('adminSetBaseDefValue'),
    adminSetBaseMaxHpValueInput: getEl('adminSetBaseMaxHpValue'),
    adminSetBaseMaxMpValueInput: getEl('adminSetBaseMaxMpValue'),
    adminSetLevelBtn: getEl('admin-set-level-btn'),
    adminGiveExpBtn: getEl('admin-give-exp-btn'),
    adminGiveColBtn: getEl('admin-give-col-btn'),
    adminSetBaseAtkBtn: getEl('admin-set-base-atk-btn'),
    adminSetBaseDefBtn: getEl('admin-set-base-def-btn'),
    adminSetBaseMaxHpBtn: getEl('admin-set-base-max-hp-btn'),
    adminSetBaseMaxMpBtn: getEl('admin-set-base-max-mp-btn'),
    adminItemQuickSelect: getEl('adminItemQuickSelect'),
    adminItemIdValueInput: getEl('adminItemIdValue'),
    adminItemQuantityValueInput: getEl('adminItemQuantityValue'),
    adminShowItemDetailsBtn: getEl('admin-show-item-details-btn'),
    adminGiveItemBtn: getEl('admin-give-item-btn'),
    adminItemDetailsPreviewDiv: getEl('adminItemDetailsPreview'),
    adminFloorNumberValueInput: getEl('adminFloorNumberValue'),
    adminGrantFloorAccessBtn: getEl('admin-grant-floor-access-btn'),
    adminRevokeFloorAccessBtn: getEl('admin-revoke-floor-access-btn'),
    adminUnlockedFloorsListDiv: getEl('adminUnlockedFloorsList'),
    adminQuestDefinitionSelect: getEl('adminQuestDefinitionSelect'),
    adminQuestIdInput: getEl('adminQuestId'),
    adminQuestTitleInput: getEl('adminQuestTitle'),
    adminQuestDescriptionInput: getEl('adminQuestDescription'),
    adminQuestTypeSelect: getEl('adminQuestType'),
    adminQuestTargetIdInput: getEl('adminQuestTargetId'),
    adminQuestTargetCountInput: getEl('adminQuestTargetCount'),
    adminQuestLevelReqInput: getEl('adminQuestLevelReq'),
    adminQuestRewardColInput: getEl('adminQuestRewardCol'),
    adminQuestRewardExpInput: getEl('adminQuestRewardExp'),
    adminQuestRewardItemIdInput: getEl('adminQuestRewardItemId'),
    adminQuestRewardItemQtyInput: getEl('adminQuestRewardItemQty'),
    adminLoadQuestForEditingBtn: getEl('admin-load-quest-for-editing-btn'),
    adminDeleteQuestDefinitionBtn: getEl('admin-delete-quest-definition-btn'),
    adminSaveQuestDefinitionBtn: getEl('admin-save-quest-definition-btn'),
    adminClearQuestDefinitionFormBtn: getEl('admin-clear-quest-definition-form-btn'),
    adminPlayerQuestSelect: getEl('adminPlayerQuestSelect'),
    adminCompletePlayerQuestBtn: getEl('admin-complete-player-quest-btn'),
    adminResetPlayerQuestBtn: getEl('admin-reset-player-quest-btn'),
    adminPanelMessage: getEl('adminPanelMessage'),
    closeAdminPanelModalBtn: getEl('close-admin-panel-modal-btn'),


    // Elementos de la Wiki
    charactersGridDisplay: getEl('characters-grid-display'),
    weaponsGridDisplay: getEl('weapons-grid-display'),
    floorsInfoContainer: getEl('floors-info-container'),
    guildsInfoContainer: getEl('guilds-info-container'),
    
    // Enlaces de navegación (para event listeners)
    navPersonajesLink: getEl('nav-personajes-link'),
    navArsenalLink: getEl('nav-arsenal-link'),
    navPisosLink: getEl('nav-pisos-link'),
    navGremiosLink: getEl('nav-gremios-link'),
    navGameLink: getEl('nav-game-link'),

    // Elementos Audiovisuales y de Notificación
    backgroundMusic: getEl('background-music'),
    musicToggleBtn: getEl('music-toggle-btn'),
    notificationArea: getEl('notification-area'),
    particlesContainer: getEl('particles'),
};